
services:
  tg_bot:
    build:
      context: .  # Указываем контекст сборки для tg-bot
      dockerfile: Dockerfile
    container_name: tg-bot-service
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - TGBOT_TOKEN
      - SOURCE_CHAT_ID
      - TARGET_CHANNEL_ID
