# Dockerfilew

# Используем базовый образ Python
FROM python:3.11-slim

# Копируем скрипт внутрь контейнера
COPY req.txt .

RUN pip install --no-cache-dir -r req.txt

# Копируем весь код бота в контейнер
COPY . .

# Запускаем скрипт
CMD ["python3", "run.py"]
